


on:
  push:
    branches:
      - master
      - main
    paths:
      - 'EasyPIM/**'
  pull_request:
    branches:
      - master
      - main
    paths:
      - 'EasyPIM/**'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Prerequisites
      run: .\build\vsts-prerequisites.ps1
      shell: powershell
    - name: Validate EasyPIM Only
      run: |
        $changed = git diff --name-only ${{ github.event.before }} ${{ github.sha }} | Select-String -Pattern '^EasyPIM/'
        if ($changed) { .\build\vsts-validate.ps1 } else { Write-Host 'No EasyPIM changes detected, skipping validation.' }
      shell: pwsh
    - name: Build EasyPIM Only
      run: |
        $changed = git diff --name-only ${{ github.event.before }} ${{ github.sha }} | Select-String -Pattern '^EasyPIM/'
        if ($changed) { .\build\vsts-build.ps1 -ApiKey $env:APIKEY } else { Write-Host 'No EasyPIM changes detected, skipping build.' }
      shell: pwsh
      env:
        APIKEY: ${{ secrets.ApiKey }}