
on:
  push:
    tags:
      - 'orchestrator-v*'
  pull_request:
    paths:
      - 'EasyPIM.Orchestrator/**'

jobs:
  build-orchestrator:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install EasyPIM Core from Gallery
        run: Install-Module -Name EasyPIM -Force -Scope CurrentUser
        shell: pwsh
      - name: Install Prerequisites
        run: .\build\vsts-prerequisites.ps1
        shell: powershell
      - name: Install EasyPIM Core from Gallery
        run: Install-Module -Name EasyPIM -Force -Scope CurrentUser
        shell: pwsh
      - name: Validate Orchestrator Only
        run: |
          $changed = git diff --name-only ${{ github.event.before }} ${{ github.sha }} | Select-String -Pattern '^EasyPIM.Orchestrator/'
          if ($changed) { .\build\vsts-validate.ps1 } else { Write-Host 'No Orchestrator changes detected, skipping validation.' }
        shell: pwsh
      - name: Build Orchestrator Only
        run: |
          $changed = git diff --name-only ${{ github.event.before }} ${{ github.sha }} | Select-String -Pattern '^EasyPIM.Orchestrator/'
          if ($changed) { .\EasyPIM.Orchestrator\build\vsts-build-orchestrator.ps1 -ApiKey $env:APIKEY } else { Write-Host 'No Orchestrator changes detected, skipping build.' }
        shell: pwsh
        env:
          APIKEY: ${{ secrets.ApiKey }}

      - name: Publish Orchestrator Module to PowerShell Gallery
        if: startsWith(github.ref, 'refs/tags/orchestrator-v')
        env:
          NUGET_API_KEY: ${{ secrets.POWERSHELL_GALLERY_API_KEY }}
        run: |
          Install-Module -Name PowerShellGet -Force -Scope CurrentUser
          Publish-Module -Path EasyPIM.Orchestrator -NuGetApiKey $env:NUGET_API_KEY -Repository PSGallery -Verbose
        shell: pwsh
