
on:
  push:
    tags:
      - 'orchestrator-v*'
  release:
    types: [published]

jobs:
  build-orchestrator:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install EasyPIM Core from Gallery (>=1.10.0)
        run: Install-Module -Name EasyPIM -MinimumVersion 1.10.0 -Force -Scope CurrentUser
        shell: pwsh

      - name: Install Prerequisites
        run: .\build\vsts-prerequisites.ps1
        shell: pwsh

      - name: Validate
        run: .\build\vsts-validate.ps1
        shell: pwsh

      - name: Build Orchestrator
        run: .\EasyPIM.Orchestrator\build\vsts-build-orchestrator.ps1 -ApiKey $env:APIKEY
        shell: pwsh
        env:
          APIKEY: ${{ secrets.ApiKey }}

      - name: Publish Orchestrator Module to PowerShell Gallery
        if: startsWith(github.ref, 'refs/tags/orchestrator-v')
        env:
          NUGET_API_KEY: ${{ secrets.POWERSHELL_GALLERY_API_KEY }}
        run: |
          Install-Module -Name PowerShellGet -Force -Scope CurrentUser
          Publish-Module -Path EasyPIM.Orchestrator -NuGetApiKey $env:NUGET_API_KEY -Repository PSGallery -Verbose
        shell: pwsh
