on:
  push:
    paths:
      - 'EasyPIM/**'
      - 'EasyPIM.Orchestrator/**'
      - 'shared/**'
  pull_request:
    paths:
      - 'EasyPIM/**'
      - 'EasyPIM.Orchestrator/**'
      - 'shared/**'

jobs:
  validate-easypim:
    if: github.event_name == 'push' || github.event.pull_request.head.ref == 'EasyPIM' || contains(github.event.head_commit.modified, 'EasyPIM/') || contains(github.event.head_commit.modified, 'shared/')
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Prerequisites
        run: .\build\vsts-prerequisites.ps1
        shell: powershell
      - name: Validate EasyPIM Only
        run: .\build\vsts-validate.ps1
        shell: powershell

  validate-orchestrator:
    if: github.event_name == 'push' || github.event.pull_request.head.ref == 'EasyPIM.Orchestrator' || contains(github.event.head_commit.modified, 'EasyPIM.Orchestrator/') || contains(github.event.head_commit.modified, 'shared/')
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Prerequisites
        run: .\build\vsts-prerequisites.ps1
        shell: powershell
      - name: Validate Orchestrator Only
        run: .\build\vsts-validate.ps1
        shell: powershell